version: '3'

tasks:
  build:
    cmds:
      - go build -o d2tosite .
  
  vendor:
    cmds:
      - go mod tidy
      - go mod vendor
  
  help:
    deps: [build]
    cmds:
      - ./d2tosite --help
